on: 
  push: 
     pull_request: 
 
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: npm install
      - name: Build 
        run: npm run build
  steps:
       - name: Checkout code
         uses: actions/checkout@v2
 
       - name: List directory contents
         run: ls -la
 
       - name: Set up Node.js
         uses: actions/setup-node@v2
  with:
         node-version: '20'
         name: Install dependencies
         run: npm install
         working-directory: ./
         
         -name: Run tests
  run: npm test -- --passWithNoTests
  working-directory: ./
